name: FastAPI Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy code to EC2
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r /mlops ec2-user@18.175.63.113 :~/

      - name: Deploy to EC2 and restart backend
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@18.175.63.113 << 'ENDSSH'
            cd ~/mlops-pipeline-aws
            git pull origin main
            sudo docker build -t mlops-api ./app-backend
            sudo docker stop $(sudo docker ps -q --filter ancestor=mlops-api) || true
            sudo docker run -d -p 5000:5000 mlops-api
          ENDSSH
